### ISSUE TITLE
【10 META】【Matataki Quest】密码口令红包功能

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1010]
感觉输入密码领 bounty 也可以做成一个「标准任务形式」。。
这样我可以去设计基于 Quest 的解谜游戏了。。。

_Originally posted by @lychees in https://github.com/Matataki-io/Matataki-FE/discussions/1001#discussioncomment-266936_

## 功能描述

- [x] 新增任务类型 “口令红包”，创建者需要比“自定义任务”增加一个 密码设置。
- [x] 设置密码可以选择手动输入，也可以自动生成。密码不限制字符类型不限制长度。
- [x] 任务创建完成后，创建者在任务详情页面可以查看到自己设置的密码
- [x] 做任务的勇者在任务详情页可以输入正确的密码，自动领取奖励

**Comment by guanchao71** [comment]
## 补充需求

- [ ] 优化Markdown语法展示效果，增强对超链接效果的展示
- [ ] 调整“口令红包”文字为“解谜任务”
- [ ] 为解密任务增加 宝箱图标

**Comment by guanchao71** [comment]
## 补充需求

- [ ] 增加对 标题、介绍、解锁条件的重编辑功能
- [ ] 扩展自定义任务回答长度限制为500字

**Comment by xiaotiandada** [comment]
> > ## 补充需求
> > 
> > * [x]   增加对 标题、介绍、解锁条件的重编辑功能
> > * [x]   扩展自定义任务回答长度限制为500字

可以测试 https://quest.matataki.io/

**Comment by guanchao71** [comment]
META 已经支付 ：0x20191bb35c446d69c52ddc4dd27ce628d59f89f03167a4fe816a209078f74a5f
感谢您的开发
