### ISSUE TITLE
【5 META】一些界面上的小调整

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1025]
==新人任务，老人勿接==
- [x] 移除 引导加入QQ 群的文字信息
- [x] 将目前的首页入口放到页脚处
- [x] 在页脚增加 ProductHunt 挂件显示
- [x] Fan票交易所界面和页脚弹窗层级错乱
- [x] 新增加 Discord 入口

## 1. 移除 引导加入QQ 群的文字信息

**位置1**
位于首页的第一屏 按钮下方
https://www.matataki.io/home
![image](https://user-images.githubusercontent.com/10827774/105625696-e6b10200-5e65-11eb-837a-f656dde0d535.png)

**位置2**
位于导航栏搜索框左侧
![image](https://user-images.githubusercontent.com/10827774/105625733-1f50db80-5e66-11eb-809b-860e54b89e5e.png)

## 2. 将目前的首页入口放到页脚处
1. 修改 ：将当前点击导航栏最左侧的LOGO图标跳转至 `/home`修改为 `/article`
2. 将 `/home` 页的入口放在页脚处 “使用手册” 按钮左侧，文字为 “关于瞬Matataki”

![image](https://user-images.githubusercontent.com/10827774/105625780-6343e080-5e66-11eb-9fef-4adc3caab4fa.png)

## 3. 在页脚增加 ProductHunt 挂件显示
在Matataki的页脚中添加下面的PH挂件，并采用白天模式的版本
### 样式参考
**移动端样式**
![image](https://user-images.githubusercontent.com/10827774/105625051-6092bc80-5e61-11eb-8039-e892dd49c9d3.png)
**桌面端样式**
![image](https://user-images.githubusercontent.com/10827774/105624979-e7936500-5e60-11eb-98f8-27c1a9b327cc.png)

### 挂件代码
**白天版本** （采用）
`<a href="https://www.producthunt.com/posts/matataki?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-matataki" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=281257&theme=light" alt="瞬MATATAKI - We help creators distribute SocialMoney & provide services | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>`

**黑夜版本** （弃用）
`<a href="https://www.producthunt.com/posts/matataki?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-matataki" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=281257&theme=dark" alt="瞬MATATAKI - We help creators distribute SocialMoney & provide services | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>`

## 4. Fan票交易所界面和页脚弹窗层级错乱
下图出现的层级错乱问题，出现在 https://www.matataki.io/exchange 页面，请修复。
![image](https://user-images.githubusercontent.com/10827774/105625969-f6c9e100-5e67-11eb-9bdd-099b2e0485e9.png)

## 5. 增加Discord入口
邀请链接 ： https://discord.gg/usKpE55bMy
图标样式：去iconfont上下载
hover颜色：#7289DA
默认颜色：参照其他SocialMedia图标
放置位置：Github图标右侧
![image](https://user-images.githubusercontent.com/10827774/105639214-eb9ba300-5eb1-11eb-95ee-1de5c17655e2.png)

**Comment by guanchao71** [comment]
请在完成任务之后，在下方留下 Matataki上个人主页地址 或 钱包地址，并将标签修改为“待审核”。

**Comment by xiaotiandada** [comment]
> ==新人任务，老人勿接==
> 
> * [ ]  移除 引导加入QQ 群的文字信息
> * [ ]  将目前的首页入口放到页脚处
> * [ ]  在页脚增加 ProductHunt 挂件显示
> * [ ]  Fan票交易所界面和页脚弹窗层级错乱
> * [ ]  新增加 Discord 入口
> 
> ## 1. 移除 引导加入QQ 群的文字信息
> **位置1**
> 位于首页的第一屏 按钮下方
> https://www.matataki.io/home
> ![image](https://user-images.githubusercontent.com/10827774/105625696-e6b10200-5e65-11eb-837a-f656dde0d535.png)
> 
> **位置2**
> 位于导航栏搜索框左侧
> ![image](https://user-images.githubusercontent.com/10827774/105625733-1f50db80-5e66-11eb-809b-860e54b89e5e.png)
> 
> ## 2. 将目前的首页入口放到页脚处
> 1. 修改 ：将当前点击导航栏最左侧的LOGO图标跳转至 `/home`修改为 `/article`
> 2. 将 `/home` 页的入口放在页脚处 “使用手册” 按钮左侧，文字为 “关于瞬Matataki”
> 
> ![image](https://user-images.githubusercontent.com/10827774/105625780-6343e080-5e66-11eb-9fef-4adc3caab4fa.png)
> 
> ## 3. 在页脚增加 ProductHunt 挂件显示
> 在Matataki的页脚中添加下面的PH挂件，并采用白天模式的版本
> 
> ### 样式参考
> **移动端样式**
> ![image](https://user-images.githubusercontent.com/10827774/105625051-6092bc80-5e61-11eb-8039-e892dd49c9d3.png)
> **桌面端样式**
> ![image](https://user-images.githubusercontent.com/10827774/105624979-e7936500-5e60-11eb-98f8-27c1a9b327cc.png)
> 
> ### 挂件代码
> **白天版本** （采用）
> `<a href="https://www.producthunt.com/posts/matataki?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-matataki" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=281257&theme=light" alt="瞬MATATAKI - We help creators distribute SocialMoney & provide services | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>`
> 
> **黑夜版本** （弃用）
> `<a href="https://www.producthunt.com/posts/matataki?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-matataki" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=281257&theme=dark" alt="瞬MATATAKI - We help creators distribute SocialMoney & provide services | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>`
> 
> ## 4. Fan票交易所界面和页脚弹窗层级错乱
> 下图出现的层级错乱问题，出现在 https://www.matataki.io/exchange 页面，请修复。
> ![image](https://user-images.githubusercontent.com/10827774/105625969-f6c9e100-5e67-11eb-9bdd-099b2e0485e9.png)
> 
> ## 5. 增加Discord入口
> 邀请链接 ： https://discord.gg/usKpE55bMy
> 图标样式：去iconfont上下载
> hover颜色：#7289DA
> 默认颜色：参照其他SocialMedia图标
> 放置位置：Github图标右侧
> ![image](https://user-images.githubusercontent.com/10827774/105639214-eb9ba300-5eb1-11eb-95ee-1de5c17655e2.png)

==新人任务，老人勿接== 🧑🏻‍💻

**Comment by guanchao71** [comment]
https://rinkeby.etherscan.io/tx/0x98f8a924813774552d41b729b16be416d3852b8cdeeb33e42c2cd20111f92c7b
奖励已经发放啦~感谢你对Matataki的贡献
